run:
	
	gcc -c HW12_task1.c
	gcc -o run1 HW12_task1.o
	gcc -c HW12_task2_server.c
	gcc -o runserver2 HW12_task2_server.o
	gcc -c HW12_task2_client.c
	gcc -o runclient2 HW12_task2_client.o
	gcc -c HW12_task3.c
	gcc -o run3 HW12_task3.o

clean:
	rm run*
	rm *.o
	rm fifo