run:
	gcc -c HW3_task1.c 
	gcc -o run1 HW3_task1.o
	gcc -c HW3_task2.c 
	gcc -o run2 HW3_task2.o
	gcc -c HW3_task3.c 
	gcc -o run3 HW3_task3.o
	gcc -c HW3_task4.c 
	gcc -o run4 HW3_task4.o

clean:
	rm run*
	rm *.o