run:
	gcc -c HW10_task1.c
	gcc -o run1 HW10_task1.o
	gcc -c HW10_task2.c
	gcc -o run2 HW10_task2.o
	gcc -c HW10_task3.c
	gcc -o run3 HW10_task3.o
	gcc -c test.c
	gcc -o runtest test.o

clean:
	rm run*
	rm *.o