run:
	gcc -c server4.c
	gcc -o server4 server4.o

	gcc -c tcpclient.c
	gcc -o tcpclient tcpclient.o

	gcc -c udpclient.c
	gcc -o udpclient udpclient.o

clean:
	rm *.o
	rm server4
	rm tcpclient
	rm udpclient